# Configuration File

# These are the streak MileStones that will be announced
streak-ms:
  - 5
  - 10
  - 20
  - 30
  - 50
  - 75
  - 100

# Is hunger enabled ?
hunger: false

# How many arrows are we giving the arrow kit back
arrows: 20

# What gamemode should players be set to
game-mode: "ADVENTURE"

# Do you want to clear their inventories?
clear-inventory: true

# Join Title Message Time
in: 1
stay: 7
out: 1

# Map Regen Time
regen-map: 900

# Ignore these blocks for placement
ignored-placed:
  - RESPAWN_ANCHOR