# Configuration File

# Is hunger enabled ?
hunger: false

# How many arrows are we giving the arrow kit back
arrows: 20

# What gamemode should players be set to
game-mode: "ADVENTURE"

# Do you want to clear their inventories?
clear-inventory: true

# Join Title Message Time
in: 1
stay: 7
out: 1