main: me.Tazsjah.FFA
author: Tazsjah
name: FFA
api-version: 1.19
version: 1.0.0
depend: [WorldGuard]
commands:
  spawn:
    description: Teleports player to spawn
  setwarp:
    description: Creates a new location to warp to
    permission: ffa.admin
  delwarp:
    description: Deletes a current warp
    permission: ffa.admin
  heal:
    description: Heals a player
    permission: ffa.heal
  top:
    description: Teleports player to the highest block
    permission: ffa.admin
  warp:
    description: Warps a player to a specific location
  stats:
    description: Shows the statistics for a player
  createkit:
    description: Creates a kit
    permission: ffa.admin
  kit:
    description: Gives a kit to you or a user
    permission: ffa.admin
  delkit:
    description: Deletes a kit
    permission: ffa.admin
  setinv:
    description: Sets the inventory for the server
    permission: ffa.admin
  openinv:
    description: Opens the inventory for the player
  savekit:
    description: Saves your custom kit for respawn
  remkit:
    description: Removes a kit from your kits
  setkit:
    description: Sets the main kit to spawn with
  getkit:
    description: Gives you a kit you own